### ISSUE TITLE
Error on SSL

### ISSUE THREAD

**Issue by lutfiarfianto** [Cnordbo/RECaptcha-for-Codeigniter#15]
i found this:
```
 An internal error occurred: 50FB412555F21.AC2CCCA.E7004106
```
while working on SSL?
would you please help me. Thank's a lot for your awesome stuff

**Comment by Cnordbo** [comment]
Do you have any more information on what you were trying to do when you got this error? Where the error occured e.e? 

If it happens when trying to get the HTML for the recaptcha, remember to use `recaptcha_get_html(null,true)` as this sets up the library to use googles SSL server.

**Comment by Cnordbo** [comment]
Closing this issue as its been a year without response or further issues.
